### ISSUE TITLE
modifying remote question

### ISSUE THREAD

**Issue by w-** [unifiedremote/Docs#1]
hi,

in the bundled daum potplayer remote file the commands are constants that look like
```
local WM_COMMAND 			= 0x111;
local CMD_PLAY				= 20001;
local CMD_PAUSE				= 20000;
local CMD_STOP				= 20002;
local CMD_PREVIOUS			= 10123;
local CMD_NEXT				= 10124;
local CMD_PLAY_PAUSE		= 10014;

local CMD_VOLUME_UP			= 10035;
local CMD_VOLUME_DOWN 		= 10036;

local CMD_TOGGLE_MUTE		= 10037;
local CMD_TOGGLE_PLAYLIST   = 10011;
local CMD_TOGGLE_CONTROL	= 10383;
local CMD_OPEN_FILE			= 10158;
local CMD_TOGGLE_SUBS		= 10126;
local CMD_TOGGLE_OSD		= 10351;
local CMD_CAPTURE			= 10224;
```

what do the numbers correspond do? key press codes or?
I'm trying to find out the term i should use to search for additional reference so i can add my own functionality.

thanks

**Comment by ui-philip** [comment]
Hi, this isn't really the correct github project for the question. But to answer your question, the codes are used for sending "WM_COMMAND" messages to the Window using SendMessage. 

You can try to Google for "potplayer wm_command" or "potplayer sendmessage" or similar. Alternatively you can try detecting the codes using tools like "Spy++".

If you'd like, I can help you look up the codes. But please create the issue on this github page instead: https://github.com/unifiedremote/Remotes/issues
