### ISSUE TITLE
'No disk' error on windows

### ISSUE THREAD

**Issue by ThomasSimoens** [unifiedremote/Docs#12]
Hi, I didn't really find another repo to report this bug, so I hope here's okay.

The issue I'm having is that, on Windows 10, whenever I start Unified Remote I get this error: ![error-screenshot](https://user-images.githubusercontent.com/951172/28839157-08da83fa-76f3-11e7-90ba-06e98d86e8eb.png).

I googled the message "There is no disk in the drive. Please insert a disk in drive {drive-letter}" and [apparently](https://www.accountexnetwork.com/blog/2013/08/fixing-the-there-is-no-disk-in-the-drive-error/) it's something that happens to removable drives (in my case it's a DVD drive), but can be caught.

It blocks the Unified Remote service to run, so I can't use a remote until I hit 'Continue'. Nothing major ofcourse, but would be cool if it was fixed.

If you need any more details, let me know!

**Comment by sxrxnrr** [comment]
Use USBDEVIEW (google it) and remove all unused inactive devices, reboot, try again.
