### ISSUE TITLE
Additional Icons

### ISSUE THREAD

**Issue by linonetwo** [unifiedremote/Docs#22]
I'd like to implement https://github.com/unifiedremote/Remotes/issues/120 to be something like https://iooio.io/toucharch/

I need icons for copy and paste. 

But I found only these icons https://github.com/unifiedremote/Docs/blob/master/res/icons.md 

Is it possible to send icons or image as text/base64 to the phone? And use image tag to display it in the button?

**Comment by pqvst** [comment]
You can use custom images on buttons. Simply place the image in the same folder as the remote and refer to it like this: https://github.com/unifiedremote/Docs/blob/master/controls/button.md#image

**Comment by linonetwo** [comment]
Can I create a button with both label text and image icon?

Something like:

```jsx
<grid ontap="foo_tapped">
	<label id="my_label" text="foo" />
    <button image="img.png" />
</grid>
```

And it should look like a whole, click like a whole, can I achieve that?

**Comment by linonetwo** [comment]
Can I create a button with both label text and image icon?

I had gone through all the doc but not found an answer.

I think it may be something like:

```jsx
<grid ontap="foo_tapped">
	<label id="my_label" text="foo" />
    <button image="img.png" />
</grid>
```

And it should look like a whole, click like a whole, can I achieve that?
