### ISSUE TITLE
What does keys and buttons mean?

### ISSUE THREAD

**Issue by linonetwo** [unifiedremote/Docs#23]
https://github.com/unifiedremote/Docs/blob/master/res/buttons.md and https://github.com/unifiedremote/Docs/blob/master/res/keys.md

They contain enigmatic words.

**Comment by skartknet** [comment]
A bit late to the party but 'buttons' look like mouse buttons and 'keys' keyboard keys.

**Comment by pqvst** [comment]
Correct, buttons are mouse buttons used for simulating mouse clicks:
https://github.com/unifiedremote/Docs/blob/master/libs/mouse.md

Keys are used for simulating key presses:
https://github.com/unifiedremote/Docs/blob/master/libs/keyboard.md
