### ISSUE TITLE
OS.Start() not working

### ISSUE THREAD

**Issue by ITMicaH** [unifiedremote/Docs#29]
I'm creating a remote for Zoom and I'm trying to launch Edge with the url of the meeting. I'm using this code: 

`--@help Start Zoom Meeting
actions.command1 = function ()
	os.start("C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe", "<url for meeting>");
end`

It's not working. I opened the example remote for running applications and those aren't working either. I tried the first button but calc didn't start. My other buttons are working fine (keystrokes).

I'm on a Win10 OS with server version 3.7.0.2352 (46) and the latest android app

**Comment by ITMicaH** [comment]
After rebooting my PC, my custom remote no longer shows up in the list, even though the files remain in the correct folder.  Besides the issue above it was working prior to the reboot.

**Comment by pqvst** [comment]
Are you sure that path to msedge is correct? I just checked my Windows 10 machine and I don't have that path. I got this to work though:
```
os.open("microsoft-edge:https://unifiedremote.com");
```
You could try that and replace the URL with your meeting link.

**Comment by ITMicaH** [comment]
My path is correct, it's edge chromium not the legacy version like in your
solution. And like I stated: I can't even open calc.exe this way so your
solution probably won't work for me. I'll try it anyway and let you know.
Thanks for the suggestion.

Op ma 9 nov. 2020 04:21 schreef Philip Bergqvist <notifications@github.com>:

**Comment by pqvst** [comment]
Have a look at the server logs as well after trying to open calc.exe and see if you get any errors:
http://localhost:9510/web/#/log

**Comment by ITMicaH** [comment]
I checked but no errors.  I get an error when I push the second button on the example remote because the foobar.exe is not found. It looks like the server just can|t start executables.

**Comment by ITMicaH** [comment]
I did check the Windows service checkbox during installation. I think a reinstall might help.

**Comment by ITMicaH** [comment]
Reinstalling the server without the Windows service fixed the issue

**Comment by pqvst** [comment]
Ah, interesting. Yeah, the service is pretty experimental. Thanks for the feedback at least!
