### ISSUE TITLE
Question | Is it possible to add conditional logic/loops (IF/FOR) to actions?

### ISSUE THREAD

**Issue by Gamartto** [unifiedremote/Docs#32]
Hi, 
I'm pretty new to unified remote and I've been doing some small tests based on the examples but I would like know if it is possible to enhance actions by adding logic based on the output or state of a variable/keypress/events. If so, How?

Thanks.

**Comment by Gamartto** [comment]
Upon further research a lot of stuff can be done to make things more robust
https://www.tutorialspoint.com/lua/lua_variables.htm

The many stock controls are good to know how some things work.

**Comment by pqvst** [comment]
I would also recommend having a look at the existing remotes for inspiration/guidance.
https://github.com/unifiedremote/Remotes
