### ISSUE TITLE
Can I trigger actions (in my case kb.stroke) with the physical volume rockers on android?

### ISSUE THREAD

**Issue by makkaroni470** [unifiedremote/Docs#33]

**Comment by pqvst** [comment]
Yes, you can use the `onvolumeup` and `onvolumedown` events:
https://github.com/unifiedremote/Remotes/blob/master/Main/Media/layout.xml#L2

Just specify an action name, and then define them in your remote.lua file:
https://github.com/unifiedremote/Remotes/blob/master/Main/Media/remote.lua#L5

**Comment by superamnesia** [comment]
Does it work on iOS?
in my tests the function associated to onvolumeup is not triggered.
I'd like to use iphone hw buttom to increase or decrease the volume of my kodi setup
