### ISSUE TITLE
Display button image + caption

### ISSUE THREAD

**Issue by skartknet** [unifiedremote/Docs#34]
Is it possible to display an image as a background along with the button label? I would like to identify each button with a small logo on one of the corners but still display the button caption.

**Comment by pqvst** [comment]
At the moment it is only possible to specify either an icon or text. I guess a workaround would be to add the label to the logo, or add a label above/below the button.

**Comment by skartknet** [comment]
Yep, that's what I thought :). Thanks. Great app, it's really great and the API is pretty cool.
