### ISSUE TITLE
Joytick

### ISSUE THREAD

**Issue by HalJordan** [unifiedremote/Docs#39]
What happened to the joystick library, and is there any way to get it back?

I'm assuming with that, we can set it up as a separate joystick device with X number of buttons, so that we can then map that within a game correct?

If so, that's /PRECISELY/ what I was looking into this for. Yet, I'm unable to find anything on it save for a dead link in the docs.

**Comment by pqvst** [comment]
The joystick implementation never really got off the ground properly. It works, but it might be a little buggy. The current joystick implementation only supports:

- "Look" (adjusts the primary X/Y axes
- "Rotate" (adjusts the secondary X/Y axes
- "Throttle"

Currently it does not support Joystick buttons. Although those actions can probably always be simulated using keyboard shortcuts instead.

The gaming branch in the Remotes repo includes some examples we built a while back. For example, this one is built for Microsoft Flight Simulator: https://github.com/unifiedremote/Remotes/blob/gaming/Gaming/FSX/remote.lua

If you want to enable the Joystick feature of the driver you have to add this registry key:
- HKLM
- `SYSTEM\CurrentControlSet\services\uvhid\Parameters`
- ValueName: `Joystick`
- ValueType: `dword`
- ValueData: `1`

**Comment by HalJordan** [comment]
Yeah, I should have mentioned, I'm on linux here, so that's not gonna work, and I have a throttle/joystick, I was just hoping for controls that won't interfere with other keyboard tasks in the game.

But I also feel like a numpty after taking another look at the docs for the keyboard. I've got /SO/ many keys to play with over what Windows gets(if I'm reading right), including F13-24 to play with, so I won't even interfere with the onfoot controls.

**Comment by pqvst** [comment]
I see. Yes, the Joystick is currently only applicable to Windows. I will go ahead and close this issue now.
