### ISSUE TITLE
storing secrets?

### ISSUE THREAD

**Issue by YAMLcase** [unifiedremote/Docs#43]
What's the best way to store secrets locally?  I needs to build http REST requests with a Bearer token, but don't want to store it in my remote control files.  I was thinking FS read file, but then how would I parse if I have it kept in YAML, JSON or such?

**Comment by pqvst** [comment]
You can create a `settings.prop` file for your remote. Here's an example for the VLC Web remote:
https://github.com/unifiedremote/Remotes/tree/master/Main/VLC%20Web

You can access these values from the remote, like this:
https://github.com/unifiedremote/Remotes/blob/master/Main/VLC%20Web/remote.lua#L11

You can edit the settings.prop file manually, or you can edit the values in the Server Manager (Remotes > Configure)
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/4990657/216745375-0d26d8f6-7794-47aa-b942-b3391802de51.png">
