### ISSUE TITLE
Win.list() does not return task's executable name

### ISSUE THREAD

**Issue by Chokollis** [unifiedremote/Docs#5]
I do not know if it is wanted behaviour but if I use win.list(false) and try to access the task's name attribute, I'll get an empty string.

I tried to retrieve the executable name by GetModuleFileNameEx (ffi) but this function cannot be resolved.

EDIT: Wrong repository, sorry

**Comment by pqvst** [comment]
Thanks. I've added the issue to our issue tracker. This repo is for documentation only.
