### ISSUE TITLE
[Linux] F13-F24 keys cause server crash

### ISSUE THREAD

**Issue by Xeollron** [unifiedremote/Docs#6]
When kb.stroke("f13"); or any F key above 12 is called the UR Server crashes.

Version	3.3.5.738 (41)
OS	linux
Platform	Linux 4.2.0-35-generic x86_64 (Ubuntu Gnome 15.10)

**Comment by pqvst** [comment]
Thanks. I've added the issue to our issue tracker. This repo is for documentation only.

**Comment by HalJordan** [comment]
It doesn't look like this has been fixed yet. Is that issue tracker internal only, or can we have  a link to it?
